version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: typingtest-backend
    ports:
      - "9090:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27018/typingtestdb
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: typingtest-frontend
    ports:
      - "3000:5173"
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  mongo-data:

